default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: demo
  password: demo
  host: db
  port: 5432

development:
  <<: *default
  database: todo-rails-api-development

test:
  <<: *default
  database: todo-rails-api-test

production:
  <<: *default
  database: demo
  username: demo
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 35.243.107.90
